set nu
set hlsearch
set ruler
set showmode
syntax on

set nocompatible " Powerline need.
set encoding=utf-8 " Necessary to show Unicode glyphs
"filetype off

set ru
set confirm
set history=100
set cursorline
set laststatus=2 "Powerline need.
set statusline=%4*%<\%m%<[%f\%r%h%w]\ [%{&ff},%{&fileencoding},%Y]%=\[Position=%l,%v,%p%%]

set tabpagemax=100

map <C-n> :tabnext <CR>
nmap <C-t> :tabnew . <CR>

" Vundle
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" Let Vundle manage Vundle
" required!
Bundle 'gmarik/vundle'

" My Bundles here:
Bundle 'Lokaltog/vim-powerline'


